name: examples/solari-arena-py

on:
  pull_request:
  push:
    paths:
      - "examples/solari-arena-py/**"
      - ".github/workflows/solari-arena-py.yml"

jobs:
  examples-solari-arena-py:
    name: examples/solari-arena-py
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/solari-arena-py
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: pip install -r requirements.txt
      - name: pytest
        run: pytest
        env:
          SOLARI_API_KEY: ""
